

services:
  reverse-proxy:
    build: ./nginx
    # image: nginx-proxy
    ports:
      - 8080:80
    depends_on:
      - catalogue
      - payment
      - users

  catalogue:
    build: ./CatalogueService
    image: catalogue-service
    container_name: catalogue-service

  analytics:
    build: ./Analytics
    image: analytics-service
    container_name: analytics-service

  payment:
    build: ./PaymentService
    image: payment-service
    container_name: payment-service

  users:
    build: ./UserService
    image: user-service
    container_name: user-service

  mongo-container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - catalogue_volume:/data/db

  mssql-container:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword123"
    ports:
      - 1433:1433
    volumes:
      - sqlserverdata:/var/opt/mssql

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka-data:/bitnami/kafka

volumes:
  catalogue_volume:
  sqlserverdata:
  kafka-data: