

services:
  reverse-proxy:
    build: ./nginx
    # image: nginx-proxy
    ports:
      - 8080:80
    depends_on:
      - catalogue
      - payment
      - users

  catalogue:
    build: ./CatalogueService
    image: catalogue-service
    container_name: catalogue-service

  analytics:
    build: ./Analytics
    image: analytics-service
    container_name: analytics-service

  payment:
    build: ./PaymentService
    image: payment-service
    container_name: payment-service

  users:
    build: ./UserService
    image: user-service
    container_name: user-service

  mongo-container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - catalogue_volume:/data/db

  mssql-container:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword123"
    ports:
      - 1433:1433
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  catalogue_volume:
  sqlserverdata: