

services:
  reverse-proxy:
    build: ./nginx
    # image: nginx-proxy
    ports:
      - 80:80
    depends_on:
      - catalogue
      - payment
      - user

  catalogue:
    build: ./CatalogueService
    image: catalogue-service
    container_name: catalogue-service

  analytics:
    build: ./Analytics
    image: analytics-service
    container_name: analytics-service

  payment:
    build: ./PaymentService
    image: payment-service
    container_name: payment-service

  user:
    build: ./UserService
    image: user-service
    container_name: user-service

  mongo-container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - catalogue_volume:/data/db

volumes:
  catalogue_volume:
  sqlserverdata: