# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/carsim.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'app/proto/carsim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pp/proto/carsim.proto\"5\n\x10\x43olourSimRequest\x12\r\n\x05image\x18\x01 \x02(\x0c\x12\x12\n\nrgb_colors\x18\x02 \x03(\x05\"\"\n\x11\x43olourSimResponse\x12\r\n\x05iamge\x18\x01 \x02(\x0c\x32\x41\n\x06\x43\x61rSim\x12\x37\n\x0eSimulateColour\x12\x11.ColourSimRequest\x1a\x12.ColourSimResponse')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.carsim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLOURSIMREQUEST']._serialized_start=26
  _globals['_COLOURSIMREQUEST']._serialized_end=79
  _globals['_COLOURSIMRESPONSE']._serialized_start=81
  _globals['_COLOURSIMRESPONSE']._serialized_end=115
  _globals['_CARSIM']._serialized_start=117
  _globals['_CARSIM']._serialized_end=182
# @@protoc_insertion_point(module_scope)
