services:
  user-service:
    build: .
    # image: user-service:latest
    container_name: user-service
    ports:
      - "8080:8080"
    # depends_on:
    #   - user-db


  # user-db:
  #   image: mysql:8.4.0
  #   volumes:
  #     - ./db/mysql_data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: asdasd
  #   ports: 
  #     - 3306:3306

  # phpmyadmin:
  #   depends_on:
  #     - user-db
  #   image: phpmyadmin/phpmyadmin:5.2.1
  #   ports:
  #     - 8081:80
  #   volumes:
  #     - ./db/phpMyAdmin-new:/var/www/html
  #   environment:
  #     PMA_HOST: user-db
  #     MYSQL_ROOT_PASSWORD: asdasd
  #     UPLOAD_LIMIT: 1G
  #     PHP_UPLOAD_MAX_FILESIZE: 1G
  #     PHP_POST_MAX_SIZE: 1G

